# Generated by Django 2.2.6 on 2019-11-14 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20191111_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='article.Article', verbose_name='meqale')),
                ("comment_author" , models.CharField(max_length=50,verbose_name="isim")),
                ("comment_content" , models.CharField(max_length=200,verbose_name="yorumm")),
                ("comment_date" , models.DateTimeField(auto_now_add=True)),
      
            
            ],
        
        ),
    ]
