# Generated by Django 2.2.6 on 2019-11-14 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20191115_0204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
    ]
